### ISSUE TITLE
Suggestion: use Pandas MultiIndex when possible

### ISSUE THREAD

**Issue by batterseapower** [Knoema/knoema-python-driver#1]
Around https://github.com/Knoema/knoema-python-driver/blob/master/knoema/data_reader.py#L86 you flatten the "column headers" into a simple "-" separated string. It would probably be better to output a DataFrame with a MultiIndex (https://pandas.pydata.org/pandas-docs/stable/generated/pandas.MultiIndex.html) instead, to make it easier to reshape the dimensions on the client side.

**Comment by PavelPimenov** [comment]
Fixed in version 1.0.0b1
