### ISSUE TITLE
Large requests should raise exception

### ISSUE THREAD

**Issue by batterseapower** [Knoema/knoema-python-driver#2]
If you request too much data, the /api/1.0/data/pivot endpoint returns HTTP status 200 and the string 'Underlying data is very large. Can\\'t create visualization.'

Ideally the API would actually raise an error in this case, which the client could detect. If not, I guess the Python code should try to spot that the response is just a string as opposed to a JSON object, and raise it as an exception. Right now you just get "TypeError: string indices must be integers" from api_definitions.py:156

**Comment by PavelPimenov** [comment]
Fixed in version 1.0.0b1
